#### Decision tree Regressor
- gives better results for non linear data

In [1]:
import pandas as pd
df=pd.read_csv("1000_companies.csv")
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [2]:
import matplotlib.pyplot as plt
x1=df["R&D Spend"]
y1=df["Profit"]
plt.scatter(x1,y1)
plt.show()

<Figure size 640x480 with 1 Axes>

In [3]:
df.isna().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["State"]=le.fit_transform(df["State"])
x=df.iloc[:,0:4]
y=df["Profit"]

from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor()
model.fit(x,y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [5]:
y_predict=model.predict(x)
y_predict

array([192261.83   , 191792.06   , 191050.39   , 182901.99   ,
       166187.94   , 156991.12   , 156122.51   , 155752.6    ,
       152211.77   , 149759.96   , 146121.95   , 144259.4    ,
       141585.52   , 134307.35   , 132602.65   , 129917.04   ,
       126992.93   , 125370.37   , 124266.9    , 122776.86   ,
       118474.03   , 111313.02   , 110352.25   , 108733.99   ,
       108552.04   , 107404.34   , 105733.54   , 105008.31   ,
       103282.38   , 101004.64   ,  99937.59   ,  97483.56   ,
        97427.84   ,  96778.92   ,  96712.8    ,  96479.51   ,
        90708.19   ,  89949.14   ,  81229.06   ,  81005.76   ,
        78239.91   ,  77798.83   ,  71498.49   ,  69758.98   ,
        65200.33   ,  64926.08   ,  49490.75   ,  42559.73   ,
        35673.41   ,  14681.4    , 123485.2464 ,  82155.48418,
       125867.0108 , 104976.1696 ,  89803.10053,  75297.23305,
       114284.5283 , 171985.0761 ,  72337.96774, 169566.5772 ,
       158670.9451 , 114522.8756 ,  85842.60573, 101106

In [6]:
from sklearn.metrics import r2_score
print(r2_score(y,y_predict))

1.0


In [ ]:
import matplotlib.pyplot as plt
from sklearn import tree
plt.figure()
tree.plot_tree(model,feature_names=x.columns)
plt.show()

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=25)
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor()
model.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [9]:
y_predict=model.predict(x_test)
y_predict

array([ 64966.2875 ,  42559.73   , 168760.9805 ,  50428.81124,
        52225.38599, 145965.9238 , 112883.4905 , 162399.9269 ,
        83356.61784, 111764.3688 ,  72657.47271,  68210.88613,
        88481.51178,  60368.49134, 155881.6838 , 167373.6113 ,
       145073.1894 , 141408.2794 , 175999.3913 , 119914.3085 ,
       171416.9724 ,  96712.8    , 153825.4044 ,  51690.5996 ,
        55832.20416,  99301.96628, 152175.7678 , 110963.8978 ,
        58694.93455,  65204.63479, 149669.2769 ,  98368.22581,
        90808.60147,  51324.1086 , 114373.3746 , 154765.9792 ,
       118474.03   , 115751.3466 ,  82229.80752, 110963.8978 ,
       176623.024  , 163155.1205 ,  60947.70089, 142762.3312 ,
        65743.69265,  91977.27207,  59803.80475, 172966.6569 ,
        92903.32391,  77837.89559, 168285.1402 , 181258.409  ,
        65513.03398,  70232.13951,  67473.63267, 114373.3746 ,
        90108.93684, 107682.5646 , 128265.0066 ,  88072.30621,
       176623.024  , 120412.3603 , 161630.2104 ,  99301

In [10]:
r2_score(y_test,y_predict)

0.9642959658423127

#### Random Forest
- in decision tree -overfitting----model get trained well
- randomforest will overcome that overfitting in decision tree
- gives better accuracy when compared to other algorithms
- it works better if there is also missing values

***Random Forest Classifier***

In [13]:
df=pd.read_csv("bird.csv")
df.head()

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
0   0  80.78  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   SW
1   1  88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
2   2  79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
3   3  77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
4   4  62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW

In [14]:
df.isna().sum()

id       0
huml     1
humw     1
ulnal    3
ulnaw    2
feml     2
femw     1
tibl     2
tibw     1
tarl     1
tarw     1
type     0
dtype: int64

In [20]:
import numpy as np

In [21]:
df=df.replace(np.nan,0.0)
df.isna().sum()

id       0
huml     0
humw     0
ulnal    0
ulnaw    0
feml     0
femw     0
tibl     0
tibw     0
tarl     0
tarw     0
type     0
dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["type"]=le.fit_transform(df["type"])
df.head()

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw  type
0   0  80.78  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84     3
1   1  88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01     3
2   2  79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34     3
3   3  77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41     3
4   4  62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13     3

In [25]:
df["type"].unique()

array([3, 5, 4, 1, 0, 2], dtype=int64)

In [32]:
x=df.iloc[:,1:11]
y=df["type"]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [33]:
y_pred=model.predict(x_test)
y_pred

array([3, 5, 3, 2, 2, 0, 5, 5, 5, 2, 2, 3, 3, 2, 3, 3, 3, 1, 5, 2, 3, 3,
       3, 2, 5, 5, 3, 0, 3, 2, 2, 2, 1, 2, 3, 2, 2, 1, 1, 3, 2, 2, 1, 0,
       2, 0, 2, 1, 0, 3, 0, 5, 0, 2, 2, 2, 0, 2, 2, 2, 3, 1, 4, 1, 2, 1,
       0, 5, 2, 2, 2, 2, 4, 3, 0, 2, 2, 2, 3, 3, 3, 4, 3, 3, 2, 1, 3, 4,
       5, 3, 2, 2, 2, 2, 1, 3, 0, 2, 3, 2, 3, 5, 1, 3, 2, 1, 2, 3, 1, 3,
       1, 3, 2, 0, 2, 2, 1, 2, 0, 0, 2, 2, 2, 3, 3, 1])

In [34]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8174603174603174
[[11  0  2  0  0  0]
 [ 1 13  0  0  0  0]
 [ 0  1 40  0  0  0]
 [ 0  1  1 27  0  3]
 [ 0  1  1  0  4  0]
 [ 2  1  3  6  0  8]]


***Random Forest Regressor***

In [35]:
df=pd.read_csv("salary.csv")
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [38]:
x=df["YearsExperience"].values
x=x.reshape(-1,1)
y=df["Salary"]
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
model.fit(x,y)

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [39]:
y_pred=model.predict(x)

In [40]:
from sklearn.metrics import r2_score
print(r2_score(y,y_pred))

0.9897399622341074


***Apply the fruits dataset to any of the calssification algorithms***